### ISSUE TITLE
Model downloader - too many icons, unclear what should happen

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/archive.bioimage.io#126] opened 2021-06-25 06:21 UTC
Hi @oeway,

I was trying to use the model downloader to download some of @constantinpape latest models from the model zoo:

![2021-06-25_08-17_package](https://user-images.githubusercontent.com/24434157/123379083-e4c2aa80-d58d-11eb-8d20-b6d668e75a39.png)

In the above screenshot

* clicking the leftmost ilastik logo does not produce a download (button is there, nothing happens on clicking it)
* clicking the deepimagej logo does not produce a download (button is there, nothing happens on clicking it)
* clicking the right ilastik logo does something! But the package can not be used: the source file `unet.py` is missing (at least)
  * zipping takes a long time...
* selecting weight format pytorch does nothing (or is super slow)
* selecting weight format torchscript does nothing (or is super slow)

**Comment by constantinpape** [comment] 2021-06-25 08:24
I can reproduce this issue (also for other models, I tried `IsbiBoundaryModel`, `DsbNucleiBoundaryModel` and `3d Unet arabidopsis`).

Here's some of the errors from the console:
```
Source map error: Error: Invalid URL: webpack://[name]/webpack/universalModuleDefinition
Resource URL: https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js
Source Map URL: imjoy-rpc.min.js.map

TypeError: spec is null
    VueJS 10
    <anonymous> https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js line 1 > eval:191
    execute https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    _setupMessageHanlders https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    _fire https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    handleEvent https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    connect https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    setupIframe https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    l https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    l https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    n https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    d https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    onload https://lib.imjoy.io/default_base_frame.html?version=0.3.6&id=BioImageIO-Packager_e6z8w1624609206027_yymth1624609206029:1
    promise callback*onload https://lib.imjoy.io/default_base_frame.html?version=0.3.6&id=BioImageIO-Packager_e6z8w1624609206027_yymth1624609206029:1
vue.min.js:6:11113
TypeError: spec is null
    VueJS 15
    run https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js line 1 > eval:264
    _setupMessageHanlders https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    _fire https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    handleEvent https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    connect https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    setupIframe https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    l https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    l https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    n https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    d https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    onload https://lib.imjoy.io/default_base_frame.html?version=0.3.6&id=BioImageIO-Packager_e6z8w1624609206027_yymth1624609206029:1
    promise callback*onload https://lib.imjoy.io/default_base_frame.html?version=0.3.6&id=BioImageIO-Packager_e6z8w1624609206027_yymth1624609206029:1
vue.min.js:6:11113
XHRGEThttps://sandbox.zenodo.org/api/files/781dc5dd-1ede-4d9d-9610-09bc526da6bc/export_boundaries/weights.torchscript
[HTTP/1.1 404 NOT FOUND 184ms]

Uncaught (in promise) Error: Request failed with status code 404
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    onreadystatechange https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    promise callback*r.prototype.request https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    fetchFile https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js line 1 > eval:53
    downloadModel https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js line 1 > eval:164
    download https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js line 1 > eval:230
    VueJS 25
    init https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js line 1 > eval:210
    run https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js line 1 > eval:265
    _setupMessageHanlders https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    _fire https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    handleEvent https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    connect https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    setupIframe https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    l https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    l https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    n https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    d https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js:1
    onload https://lib.imjoy.io/default_base_frame.html?version=0.3.6&id=BioImageIO-Packager_e6z8w1624609206027_yymth1624609206029:1
    promise callback*onload https://lib.imjoy.io/default_base_frame.html?version=0.3.6&id=BioImageIO-Packager_e6z8w1624609206027_yymth1624609206029:1
axios.min.js:2:9633
XHRGEThttps://sandbox.zenodo.org/api/files/781dc5dd-1ede-4d9d-9610-09bc526da6bc/export_boundaries/weights.torchscript
[HTTP/1.1 404 NOT FOUND 43ms]

Uncaught (in promise) Error: Request failed with status code 404
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    onreadystatechange https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    promise callback*r.prototype.request https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    exports https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js:2
    fetchFile https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js line 1 > eval:53
    downloadModel https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js line 1 > eval:164
    download https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js line 1 > eval:230
    VueJS 25
    download https://cdn.jsdelivr.net/npm/imjoy-rpc@0.3.6/dist/imjoy-rpc.min.js line 1 > eval:240
    VueJS 5
```

**Comment by oeway** [comment] 2021-06-25 14:26
@constantinpape Cloud you fix the manifest file in this deposit: https://sandbox.zenodo.org/record/865618?: 
```yaml
weights:
  pytorch_script:
    sha256: 2faf27757065bcdc03bb792771ae65a656b792507cd2054c0c3a49fcacb31eab
    source: export_boundaries/weights.torchscript #<---------------- Here should be weights.torchscript 
```

**Comment by constantinpape** [comment] 2021-06-25 14:49
@oeway I see, that's probably a bug in my script that generates the yaml.

I don't have time to update this now (and I am not here next week). 

For now, I have made a new clean deposit for the ISBI model: https://sandbox.zenodo.org/record/871342#.YNXrrDqxVH4, could you please accept it to the community so that we can check if the download works with this one?
(We will then remove the earlier model)

**Comment by constantinpape** [comment] 2021-07-13 12:34
Copying current issues from gitter (some duplication with the issues raised here already):
- ilastik is listed twice, I think because it supports both weight formats, but should only be listed once and only download the pytorch state dict weights
- the "sampleInput" and "sampleOutput" images are not packaged
- general observation, zipping takes quite long compared to doing it locally

**Comment by constantinpape** [comment] 2021-07-13 16:36
@oeway I found another issue with the packager: the files specified in `attachments` are not packaged.
See for example this model: https://bioimage.io/#/?id=10.5072%2Fzenodo.880273, it specifies a macro file in the attachments, but this file is not included by the packager.

**Comment by oeway** [comment] 2021-07-13 16:58
@constantinpape could you try to change the group name from 'macro' to 'files', the packager assumes the attached files are placed under attachments.files.

FYI: if it's a weight format specific attachments, you can also add it under the attachments key of the weight format.

**Comment by constantinpape** [comment] 2021-07-13 17:08
> 'macro' to 'files', the packager assumes the attached files are placed under attachments.files.

Ok, will do.

**Comment by oeway** [comment] 2021-07-13 17:23
> ilastik is listed twice, I think because it supports both weight formats, but should only be listed once and only download the pytorch state dict weights

Fixed in both the general packager and the ilastik one!

> the "sampleInput" and "sampleOutput" images are not packaged

Same as above.

> general observation, zipping takes quite long compared to doing it locally

No good solution yet, when the files are large it does take some time to make the package.

**Comment by oeway** [comment] 2021-07-13 17:35
This is all fixed! Please reopen if it doesn't work.

**Closed as completed by oeway** 2021-07-13 17:35 UTC

**Comment by constantinpape** [comment] 2021-07-14 09:21
@oeway thanks for fixing this, I think we should still think about solutions to the zipping, i will make another issue about this.

**Comment by oeway** [comment] 2021-07-14 09:26
> @oeway thanks for fixing this, I think we should still think about solutions to the zipping, i will make another issue about this.

It might already faster since I reduced the compression level from 9 to 1 or no compression. Please give it another test.

**Comment by constantinpape** [comment] 2021-07-14 09:27
> It might already faster since I reduced the compression level from 9 to 1 or no compression. Please give it another test.

No, it did not get significantly faster; I have just tested it, see #145.
