### ISSUE TITLE
Upload is broken

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#224] opened 2022-01-15 19:42 UTC
This is what happens when clicking "Upload as new deposit":

![Screenshot from 2022-01-15 20-40-04](https://user-images.githubusercontent.com/4263537/149635623-830f8682-9a92-407d-874c-36559d8b58d5.png)

I tested with two models and it fails for both, for example this one: https://oc.embl.de/index.php/s/KtXrlvh1IjqzX9D.

**Comment by oeway** [comment] 2022-01-18 09:11
Hi, I cannot reproduce the issue, both chrome and firefox worked for me:
<img width="1552" alt="Screen Shot 2022-01-18 at 10 06 04 AM" src="https://user-images.githubusercontent.com/478667/149906076-95fe4aac-050a-437f-a3ca-12e0959f365f.png">

**Comment by oeway** [comment] 2022-01-18 09:17
Oh, wait, I think I know what happening now, it's because of a PR made by the dependabot, let's see if this can fix it: https://github.com/bioimage-io/bioimage.io/pull/225  I cannot reproduce it before because my local dependencies are outdated. I can reproduce the issue if I do a refresh with `npm install`.

Please try it again with 0.4.2 (you can check the version here: https://bioimage.io/#/about)

**Comment by oeway** [comment] 2022-01-18 09:24
I tried it and it works with bioimage.io, will close this issue now, feel free to reopen if the issue still exists.

**Closed as completed by oeway** 2022-01-18 09:24 UTC
