### ISSUE TITLE
Packager not functioning?

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/archive.bioimage.io#230] opened 2022-01-26 12:30 UTC
Hi @oeway,

I'm not sure this is an issue for everyone but even after a couple of refreshes, I cannot download [this model](https://bioimage.io/#/?id=10.5281%2Fzenodo.5749843) from the model zoo, see screenshot:

![image](https://user-images.githubusercontent.com/24434157/151162663-5ee5b8fb-20c5-4e2c-839d-1436bcdbba60.png)

_maybe_ some traceback?!

<details>

```
Error in Plugin BioImageIO-Packager_iztp21643200019501_0gy541643200019505: <BioImageIO-Packager>: (Error: YAMLException: end of the stream or a document separator is expected (9:25)

  6 |     <title>Page not found &middot; GitHub Pages</title>
  7 |     <style type="text/css" media="screen">
  8 |       body {
  9 |         background-color: #f1f1f1;
------------------------------^
 10 |         margin: 0;
 11 |         font-family: "Helvetica Neue", Helvetica, Arial ... || "Error.") imjoy-core.min.js:278:12170
    error imjoy-core.min.js:278
    renderWindow imjoy-core.min.js:278
    (Async: promise callback)
    renderWindow imjoy-core.min.js:278
    (Async: promise callback)
    renderWindow imjoy-core.min.js:278
    emit imjoy-core.min.js:1
    _setupRPC imjoy-core.min.js:278
    _setupConnection imjoy-core.min.js:278
    _fire imjoy-core.min.js:1
    _messageHandler imjoy-core.min.js:269
    connect imjoy-core.min.js:269
    _setupConnection imjoy-core.min.js:278
    _setupViaIframe imjoy-core.min.js:278
    ce imjoy-core.min.js:278
    renderWindow imjoy-core.min.js:278
    renderWindow imjoy-core.min.js:278
    createWindow imjoy-core.min.js:278
    (Async: setTimeout handler)
    createWindow imjoy-core.min.js:278
    (Async: promise callback)
    createWindow imjoy-core.min.js:278
    createWindow imjoy-core.min.js:278
    createWindow imjoyBasicApp.js:62
    run imjoy-core.min.js:278
    e app.793a9f4c.js:1
    l chunk-vendors.7ca7a943.js:51127
    n chunk-vendors.7ca7a943.js:51127
    t chunk-vendors.7ca7a943.js:51127
    n chunk-vendors.7ca7a943.js:1
    s chunk-vendors.7ca7a943.js:1
    (Async: promise callback)
    n chunk-vendors.7ca7a943.js:1
    s chunk-vendors.7ca7a943.js:1
    o chunk-vendors.7ca7a943.js:1
    o chunk-vendors.7ca7a943.js:1
    y app.793a9f4c.js:1
    w app.793a9f4c.js:1
    n app.793a9f4c.js:1
    l chunk-vendors.7ca7a943.js:51127
    n chunk-vendors.7ca7a943.js:51127
    t chunk-vendors.7ca7a943.js:51127
    n chunk-vendors.7ca7a943.js:1
    s chunk-vendors.7ca7a943.js:1
    (Async: promise callback)
    n chunk-vendors.7ca7a943.js:1
    s chunk-vendors.7ca7a943.js:1
    o chunk-vendors.7ca7a943.js:1
    o chunk-vendors.7ca7a943.js:1
    run app.793a9f4c.js:1
    click app.793a9f4c.js:1
    it chunk-vendors.7ca7a943.js:27577
    i chunk-vendors.7ca7a943.js:27577

```

</details>

**Comment by oeway** [comment] 2022-01-26 14:12
Hey, thanks for the report.

It seems the packager got some unexpected response from github pages, however, I cannot reproduce the issue. Here is what I see:
<img width="825" alt="Screen Shot 2022-01-26 at 3 09 17 PM" src="https://user-images.githubusercontent.com/478667/151178288-b61b10d6-97e1-4507-9b20-5de33c4a8f1a.png">

Maybe you are just lucky that the CI was in some intermediate state produced a broken file? Not sure, could you try it again?

**Comment by k-dominik** [comment] 2022-01-26 14:20
hmmm, now I get

<details>

```
Uncaught (in promise) Error: Oops, failed to fetch RDF file.
    e app.793a9f4c.js:1
    l chunk-vendors.7ca7a943.js:51127
    n chunk-vendors.7ca7a943.js:51127
    t chunk-vendors.7ca7a943.js:51127
    n chunk-vendors.7ca7a943.js:1
    s chunk-vendors.7ca7a943.js:1
    promise callback*n chunk-vendors.7ca7a943.js:1
    s chunk-vendors.7ca7a943.js:1
    o chunk-vendors.7ca7a943.js:1
    o chunk-vendors.7ca7a943.js:1
    Ge app.793a9f4c.js:1
    n app.793a9f4c.js:1
    l chunk-vendors.7ca7a943.js:51127
    n chunk-vendors.7ca7a943.js:51127
    t chunk-vendors.7ca7a943.js:51127
    n chunk-vendors.7ca7a943.js:1
    s chunk-vendors.7ca7a943.js:1
    o chunk-vendors.7ca7a943.js:1
    o chunk-vendors.7ca7a943.js:1
    run app.793a9f4c.js:1
    click app.793a9f4c.js:1
    it chunk-vendors.7ca7a943.js:27577
    i chunk-vendors.7ca7a943.js:27577
    _wrapper chunk-vendors.7ca7a943.js:27577
    Jo chunk-vendors.7ca7a943.js:27577
    vt chunk-vendors.7ca7a943.js:27577
    tr chunk-vendors.7ca7a943.js:27577
    T chunk-vendors.7ca7a943.js:27577
    f chunk-vendors.7ca7a943.js:27577
    Do chunk-vendors.7ca7a943.js:27577
    _update chunk-vendors.7ca7a943.js:27577
    n chunk-vendors.7ca7a943.js:27577
    get chunk-vendors.7ca7a943.js:27577
    tn chunk-vendors.7ca7a943.js:27577
    ki chunk-vendors.7ca7a943.js:27577
    $mount chunk-vendors.7ca7a943.js:27577
    init chunk-vendors.7ca7a943.js:27577
    m chunk-vendors.7ca7a943.js:27577
    f chunk-vendors.7ca7a943.js:27577
    E chunk-vendors.7ca7a943.js:27577
    f chunk-vendors.7ca7a943.js:27577
    Do chunk-vendors.7ca7a943.js:27577
    _update chunk-vendors.7ca7a943.js:27577
    n chunk-vendors.7ca7a943.js:27577
    get chunk-vendors.7ca7a943.js:27577
    tn chunk-vendors.7ca7a943.js:27577
    ki chunk-vendors.7ca7a943.js:27577
    $mount chunk-vendors.7ca7a943.js:27577
    init chunk-vendors.7ca7a943.js:27577
    m chunk-vendors.7ca7a943.js:27577
    f chunk-vendors.7ca7a943.js:27577
    E chunk-vendors.7ca7a943.js:27577
    f chunk-vendors.7ca7a943.js:27577
    Do chunk-vendors.7ca7a943.js:27577
app.793a9f4c.js:1
    n chunk-vendors.7ca7a943.js:1
    c chunk-vendors.7ca7a943.js:1
    (Async: promise callback)
    n chunk-vendors.7ca7a943.js:1
    s chunk-vendors.7ca7a943.js:1
    o chunk-vendors.7ca7a943.js:1
    o chunk-vendors.7ca7a943.js:1
    run app.793a9f4c.js:1
    click app.793a9f4c.js:1
    it chunk-vendors.7ca7a943.js:27577
    i chunk-vendors.7ca7a943.js:27577
    _wrapper chunk-vendors.7ca7a943.js:27577
    (Async: EventListener.handleEvent)
    Jo chunk-vendors.7ca7a943.js:27577
    vt chunk-vendors.7ca7a943.js:27577
    tr chunk-vendors.7ca7a943.js:27577
    T chunk-vendors.7ca7a943.js:27577
    f chunk-vendors.7ca7a943.js:27577
    Do chunk-vendors.7ca7a943.js:27577
    _update chunk-vendors.7ca7a943.js:27577
    n chunk-vendors.7ca7a943.js:27577
    get chunk-vendors.7ca7a943.js:27577
    tn chunk-vendors.7ca7a943.js:27577
    ki chunk-vendors.7ca7a943.js:27577
    $mount chunk-vendors.7ca7a943.js:27577
    init chunk-vendors.7ca7a943.js:27577
    m chunk-vendors.7ca7a943.js:27577
    f chunk-vendors.7ca7a943.js:27577
    E chunk-vendors.7ca7a943.js:27577
    f chunk-vendors.7ca7a943.js:27577
    Do chunk-vendors.7ca7a943.js:27577
    _update chunk-vendors.7ca7a943.js:27577
    n chunk-vendors.7ca7a943.js:27577
    get chunk-vendors.7ca7a943.js:27577
    tn chunk-vendors.7ca7a943.js:27577
    ki chunk-vendors.7ca7a943.js:27577
    $mount chunk-vendors.7ca7a943.js:27577
    init chunk-vendors.7ca7a943.js:27577
    m chunk-vendors.7ca7a943.js:27577
    f chunk-vendors.7ca7a943.js:27577
    E chunk-vendors.7ca7a943.js:27577
    f chunk-vendors.7ca7a943.js:27577
    Do chunk-vendors.7ca7a943.js:27577


```

</details>

note, I tried Firefox and Chrome.

**Comment by k-dominik** [comment] 2022-01-26 19:48
Hey @oeway, small update (that might help reproducing this). I found when I follow the link, the model gets highlighted with a popup - if I click the download Icon there, then the non-functioning packager window pops up. However, if I scroll through the main list and find the model there, click directly on the packager icon there, then it seems to work.

**Comment by oeway** [comment] 2022-01-26 19:56
> Hey @oeway, small update (that might help reproducing this). I found when I follow the link, the model gets highlighted with a popup - if I click the download Icon there, then the non-functioning packager window pops up. However, if I scroll through the main list and find the model there, click directly on the packager icon there, then it seems to work.

Hi, yes, I can reproduce this now, will fix it, thanks!

**Comment by oeway** [comment] 2022-01-26 20:34
@k-dominik Fixed now with https://github.com/bioimage-io/bioimage.io/pull/231 Please make sure you see 0.4.7 here: https://bioimage.io/#/about and try it again.

**Closed as completed by oeway** 2022-01-26 20:34 UTC

**Comment by k-dominik** [comment] 2022-01-27 08:39
Hey @oeway, this works now! Thank you for the quick fix!!
